version: "3.2"
services:

  web_flask:
    build: .
    restart: "no"
    command: /bin/bash -c "invenio run --host 0.0.0.0"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - /code/modules/wxpy-index/.eggs
      - /code/modules/wxpy-index/wxpy_index.egg-info
      - ./modules:/code/modules
    depends_on:
      - redis

  redis:
    image: redis

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8081:80"
    depends_on:
      - web_flask
      