version: "3.2"
services:

  web_flask:
    build: .
    restart: "no"
    command: /bin/bash -c "invenio run --host 0.0.0.0"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./modules:/code/modules
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - web_flask
      